# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf1001dc4d5b1ce780f406efb66e626e84a5a67630ff98deea1d56f66e46cc91d84adbfb976f4dc6de80a05bd4ee0cff4e9131689ca5281563d30699cf8369d

test:
  secret_key_base: f9b516556d9cff77617a6e59a463c51969d6fe8f5983f85c9485c5f071721eceddebd67b8f318446f0cb1f961b9e238aff229ad431983e53c4a61bab50cfc0fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
